Updated to use SonarQube
sonarsource-cfamily-examples/linux-cmake-gitlab-ci-sq pull request #1
Opened 2021-06-22 14:28 UTC by tomasz-kaminski-sonarsource

2021-06-22 14:29 UTC, tomasz-kaminski-sonarsource commented
Pipelines can be found here: https://gitlab.com/tomasz.kaminski/linux-cmake-gitlab-ci-sq/-/pipelines

2021-06-22 15:04 UTC, amelie-renard-sonarsource requested changes

2021-06-22 15:04 UTC, amelie-renard-sonarsource commented on .gitlab-ci.yml
> -  SONAR_SERVER_URL: "https://sonarcloud.io"
You also need to update the link on line 6

2021-06-22 15:04 UTC, amelie-renard-sonarsource commented on README.adoc
>  . Make sure that you have your token stored as a CI variable in your project (`SONAR_TOKEN`). You can request new tokens using https://sonarcloud.io/account/security/[Account/Security page].
```suggestion
. Make sure that you have your token stored as a CI variable in your project (`SONAR_TOKEN`). You can https://docs.sonarqube.org/latest/user-guide/user-token/[generate and use] new tokens in SonarQube.
```

2021-06-22 15:04 UTC, amelie-renard-sonarsource commented on .gitlab-ci.yml
> +  SONAR_SERVER_URL: <SONARQUBE_HOST_URL> # Replace <SONARQUBE_HOST_URL> with your SonarQube server URL
And replace `sonarcloud-check` with `sonarqube-check` on line 56

2021-06-23 06:23 UTC, tomasz-kaminski-sonarsource commented on .gitlab-ci.yml
> -  SONAR_SERVER_URL: "https://sonarcloud.io"
Thanks! Done.

2021-06-23 11:53 UTC, amelie-renard-sonarsource approved these changes

2021-06-23 11:54 UTC, merged